model:
  type: flux
  diffusion:
    pretrained_model_name_or_path: 'D:/FLUX.1-dev-bfloat16'
    train_unet: false
    quantization: true
  lora:
    rank: 32

train:
  max_epoch: 30
  dataset_path:
    pascal_context
  size: 256
  train_batch_size: 1
  num_workers: 4

  use_8bit_adam: false
  mixed_precision: fp16
  learning_rate: 1e-04
  max_grad_norm: 1

  warmup_method: linear
  warmup_iters: 100
  warmup_factor: 0.0001

  lr_scheduler: constant
  lr_warmup_steps: 0
  max_to_keep: 30
  period: 10

  workspace: workspace/flux_log

  gradient_accumulation_steps: 1
